Githook edit to allow push to deply to heroku
Testing the automatic deployment with githooks

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -1,11 +1,11 @@
 #!/bin/sh
 
-branch="$(git rev-parse --abbrev-ref HEAD)"
+#branch="$(git rev-parse --abbrev-ref HEAD)"
 
-if [ "$branch" = "master" ]; then
-  echo "You can't commit directly to master branch"
-  exit 1
-fi
+#if [ "$branch" = "master" ]; then
+  #echo "You can't commit directly to master branch"
+  #exit 1
+#fi
 
 
 npm run test
@@ -15,10 +15,19 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
+
 npm run linter
 
 if [ $? -ne 0 ]; then
   echo "This push has been aborted because the linter failed."
+  exit 1
+fi
+
+
+sudo dpl --provider=heroku --app=monteir4-sem3 --api-key=f6fa7d11-1d70-458e-8b60-55ea7d82e90e
+
+if [ $? -ne 0 ]; then
+  echo "This push has been aborted because the deployment failed."
   exit 1
 fi
 
